version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: realtime-price-backend
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - TICKER_COUNT=10
      - PRICE_UPDATE_INTERVAL=1.0
      - PRICE_CHANGE_RANGE=1.0
      - INITIAL_PRICE_MIN=50.0
      - INITIAL_PRICE_MAX=200.0
      - MAX_HISTORY_SIZE=1000
      - CORS_ORIGINS=["http://localhost:3000","http://localhost","http://frontend"]
      - LOG_LEVEL=INFO
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: realtime-price-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/v1
      - REACT_APP_WS_URL=ws://localhost:8000
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge